<?php

namespace ContainerMNrieWF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XEotb6IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XEotb6I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XEotb6I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'check' => ['services', '.container.private.security.password_encoder', 'get_Container_Private_Security_PasswordEncoderService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'check' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
