<?php

namespace ContainerGex31iN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCart2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.i5P4esE.App\Entity\Cart' shared service.
     *
     * @return \App\Entity\Cart
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.i5P4esE": it references class "App\\Entity\\Cart" but no such service exists.');
    }
}
