<?php

namespace ContainerMNT0x6Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9OSXpNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9OSXp_N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9OSXp_N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cartRepository' => ['privates', 'App\\Repository\\CartRepository', 'getCartRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'productRepository' => ['privates', '.errored.pKTDPmO', NULL, 'Cannot determine controller argument for "App\\Controller\\CartController::add()": the $productRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ProductRepository". Did you forget to add a use statement?'],
            'userRepository' => ['privates', '.errored.h4aptfg', NULL, 'Cannot determine controller argument for "App\\Controller\\CartController::add()": the $userRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\UserRepository". Did you forget to add a use statement?'],
        ], [
            'cartRepository' => 'App\\Repository\\CartRepository',
            'manager' => '?',
            'productRepository' => '?',
            'userRepository' => '?',
        ]);
    }
}
