<?php

namespace ContainerMNT0x6Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Xt0fx69Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Xt0fx69' shared service.
     *
     * @return \App\Controller\EntityManagerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\CartdbController::index()": the $entityManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?');
    }
}
