<?php

namespace ContainerMNT0x6Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_PKTDPmOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.pKTDPmO' shared service.
     *
     * @return \App\Controller\ProductRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\CartController::add()": the $productRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ProductRepository". Did you forget to add a use statement?');
    }
}
