<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHxJcAcU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHxJcAcU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHxJcAcU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHxJcAcU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHxJcAcU\App_KernelDevDebugContainer([
    'container.build_hash' => 'HxJcAcU',
    'container.build_id' => '97d76ac2',
    'container.build_time' => 1652359254,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHxJcAcU');
