<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWezaZUK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWezaZUK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWezaZUK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWezaZUK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWezaZUK\App_KernelDevDebugContainer([
    'container.build_hash' => 'WezaZUK',
    'container.build_id' => '06bba4b1',
    'container.build_time' => 1653311447,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWezaZUK');
