<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSznxjwm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSznxjwm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSznxjwm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSznxjwm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSznxjwm\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sznxjwm',
    'container.build_id' => '0ee186ba',
    'container.build_time' => 1652347790,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSznxjwm');
